#!/bin/bash
exec 1>&2 # Redirect output to stderr.

if test $(git diff --cached --name-only $against | wc -c) != 0; then
    changed=""
    # The commit has files added, so format them.
    for FILE in $(git diff --cached --name-only)
    do
        # Reformat only C++, and only files that weren't deleted, and not kissnet.hpp.
        if [[ "$FILE" =~ \.(cpp|h)$ && -f "$FILE" ]]; then
            old=$(mktemp /tmp/clockkit.XXXXXX)
            cp "$FILE" "$old"
            clang-format -i "$FILE"
            cmp -s "$FILE" "$old" || changed+=" ${FILE}"
            rm -f "$old"
        fi
    done
    if [[ ! -z "$changed" ]]; then
        echo "Reformatted ${changed}.  Please review, and rerun git add."
        exit 1
    fi
fi

